---
title: "CCC patient level clustering"
output: html_notebook
---
```{r}
library(Seurat)
library(liana)
library(tidyverse)
library(magrittr)
library(SingleCellExperiment)

library(viridis)
library(patchwork)
library(ggpubr)
library(cowplot)
library(rstatix)
library(pheatmap)
```

```{r}
#visualize the interactions strengthen with spp1 as sender
liana_ctr<-readRDS('~/Desktop/Shalek_Lab/Human_TB/datasets/new_liana_ctr_only_t_combined_celltype.rds')
liana_trunc_ctr<-liana_ctr%>%filter(aggregate_rank <= 0.01)

liana_TB<-readRDS('~/Desktop/Shalek_Lab/Human_TB/datasets/new_liana_run_TB_only_t_combined_celltype.rds')
liana_trunc_tb<-liana_TB%>%filter(aggregate_rank <= 0.01)


liana_trunc_ctr<-liana_trunc_ctr[,c("source", "target", "ligand.complex", "receptor.complex","natmi.edge_specificity")]
liana_trunc_tb<-liana_trunc_tb[,c("source", "target", "ligand.complex", "receptor.complex","natmi.edge_specificity")]

liana_trunc_tb <- liana_trunc_tb %>% 
        mutate(edge_weight_TB=natmi.edge_specificity)
liana_trunc_ctr <- liana_trunc_ctr %>% 
        mutate(edge_weight_CTR=natmi.edge_specificity)
liana_both<-merge(x=liana_trunc_tb,y=liana_trunc_ctr, 
        by=c("source", "target", "ligand.complex", "receptor.complex"), all=TRUE)

liana_both[is.na(liana_both)] <- 0

liana_both$edge_FC<-liana_both$edge_weight_TB/(liana_both$edge_weight_CTR+1e-4)


liana_both$edge_FC[liana_both$edge_FC == Inf] =max(liana_both$edge_FC[liana_both$edge_FC != Inf])

liana_both
```
```{r}
####  calculate mean of edge FC involving a ligand in each group,

tmp<-liana_both %>% dplyr::group_by(ligand.complex, source) %>% 
    summarise(mean_TB_edge=mean(edge_weight_TB), mean_CTR_edge=mean(edge_weight_CTR), count_FC = n())%>%ungroup()%>% unique()
min.ctr.edge<-min(tmp$mean_CTR_edge[tmp$mean_CTR_edge!=0])
tmp$mean_CTR_edge[tmp$mean_CTR_edge==0] = 0.95*min.ctr.edge
min.tb.edge<-min(tmp$mean_TB_edge[tmp$mean_TB_edge!=0])
tmp$mean_TB_edge[tmp$mean_TB_edge==0] = 0.95*min.tb.edge
average.ligand.strength<-tmp%>%mutate(mean_FC=mean_TB_edge/mean_CTR_edge)%>%mutate(log10_ligand_mean_FC = log10(mean_FC))
average.ligand.strength<-average.ligand.strength%>%mutate(abs_log10_ligand_mean_FC=abs(log10_ligand_mean_FC))
average.ligand.strength
```


for each sender, summarize an signaling  strength in each patient, then we can calculate the co-occurence 
```{r}
cell_type<-'Alveolar_Macrophages'
ligands<-liana_both%>%filter(source=='Alveolar_Macrophages')%>%pull(ligand.complex)%>%unique()
```
```{r}
obj.filtered<-readRDS('~/Desktop/Shalek_Lab/Human_TB/datasets/lung_integrated_reannotated_09262023.rds')
```

```{r}
sender_activity_df<-matrix(nrow=length(unique(liana_both$source)), ncol = 13)
rownames(sender_activity_df)<-unique(liana_both$source)
colnames(sender_activity_df)<-unique(obj.filtered$Patient)
head(sender_activity_df)
```
```{r}
for (cell_type in rownames(sender_activity_df)){
  print(cell_type)
  ligands<-liana_both%>%filter(source==cell_type)%>%pull(ligand.complex)%>%unique()
  rna_data<-FetchData(subset(obj.filtered, subset=cell.type.t_combined==cell_type),vars=ligands, slot='data' )
  Patient_info<-subset(obj.filtered, subset=cell.type.t_combined==cell_type)$Patient
  ligand_weights<-average.ligand.strength%>%filter(source==cell_type)%>%pull(abs_log10_ligand_mean_FC)
  names(ligand_weights)<-average.ligand.strength%>%filter(source==cell_type)%>%pull(
  ligand.complex)
  rna_data<-rna_data[,names(ligand_weights)]
  weighted_exp<-ligand_weights*rna_data
  patient_mean_ligand_exp<-cbind(Patient_info,weighted_exp)%>%group_by(Patient_info)%>%summarise_all(mean)%>%ungroup()
  patients_calculated<-patient_mean_ligand_exp$Patient_info
  patient_mean_ligand_exp$Patient_info<-NULL
  patient_mean_signal_strength<-rowSums(patient_mean_ligand_exp)
  print(patient_mean_signal_strength)
  sender_activity_df[cell_type,patients_calculated]<-patient_mean_signal_strength
}
```

```{r}
sender_activity_df[is.na(sender_activity_df)]<-0
sender_activity_df
```
# make heatmap based on correlation of signaling strength in patients
```{r}
sender_activity_df%>%write.csv('sender_activity_by_patient_df.csv')
sender_strength_Pearson <- cor(t(sender_activity_df), method = "pearson")
sender_strength_Pearson
correlation.heatmap <- pheatmap(sender_strength_Pearson)
Groups <- sort(cutree(correlation.heatmap$tree_row, k=4))
```

# Do a plot just for TB patients and for interactions upregulated in TB
```{r}
sender_activity_df<-matrix(nrow=length(unique(liana_trunc_tb$source)), ncol = 9)
rownames(sender_activity_df)<-unique(liana_trunc_tb$source)
colnames(sender_activity_df)<-unique(subset(obj.filtered, subset=TB=='PreviousTB')$Patient)
head(sender_activity_df)


```
```{r}

tmp<-liana_both %>%filter(edge_FC>1)%>% dplyr::group_by(ligand.complex, source) %>% 
    summarise(mean_TB_edge=mean(edge_weight_TB), mean_CTR_edge=mean(edge_weight_CTR))%>%ungroup()%>% unique()
min.ctr.edge<-min(tmp$mean_CTR_edge[tmp$mean_CTR_edge!=0])
tmp$mean_CTR_edge[tmp$mean_CTR_edge==0] = 0.95*min.ctr.edge
min.tb.edge<-min(tmp$mean_TB_edge[tmp$mean_TB_edge!=0])
tmp$mean_TB_edge[tmp$mean_TB_edge==0] = 0.95*min.tb.edge
average.ligand.strength<-tmp%>%mutate(mean_FC=mean_TB_edge/mean_CTR_edge)%>%mutate(log10_ligand_mean_FC = log10(mean_FC))
average.ligand.strength<-average.ligand.strength%>%mutate(abs_log10_ligand_mean_FC=abs(log10_ligand_mean_FC))
average.ligand.strength



# use liana result upregulated in TB only
for (cell_type in rownames(sender_activity_df)){
  print(cell_type)
  ligands<-liana_both%>%filter(edge_FC>1)%>%filter(source==cell_type)%>%pull(ligand.complex)%>%unique()
  rna_data<-FetchData(subset(obj.filtered, subset=(cell.type.t_combined==cell_type)&(TB=='PreviousTB')),vars=ligands, slot='data' )
  Patient_info<-subset(obj.filtered, subset=(cell.type.t_combined==cell_type)&(TB=='PreviousTB'))$Patient
  ligand_weights<-average.ligand.strength%>%filter(source==cell_type)%>%pull(abs_log10_ligand_mean_FC)
  names(ligand_weights)<-average.ligand.strength%>%filter(source==cell_type)%>%pull(
  ligand.complex)
  rna_data<-rna_data[,names(ligand_weights)]
  weighted_exp<-ligand_weights*rna_data
  patient_mean_ligand_exp<-cbind(Patient_info,weighted_exp)%>%group_by(Patient_info)%>%summarise_all(mean)%>%ungroup()
  patients_calculated<-patient_mean_ligand_exp$Patient_info
  patient_mean_ligand_exp$Patient_info<-NULL
  patient_mean_signal_strength<-rowSums(patient_mean_ligand_exp)
  print(patient_mean_signal_strength)
  sender_activity_df[cell_type,patients_calculated]<-patient_mean_signal_strength
}
```
```{r}
sender_activity_df[is.na(sender_activity_df)]<-0
sender_activity_df%>%write.csv('sender_activity_by_patient_TB_upregulated_df.csv')
```

